before:
  hooks:
    - go mod tidy
    - go generate ./...

dist: release

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - arm
      - arm64
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

dockers:
  - goos: linux
    dockerfile: DockerfileGoreleaser
    image_templates:
      - thomaspoignant/{{.ProjectName}}:latest
      - thomaspoignant/{{.ProjectName}}:{{ .Tag }}
      - thomaspoignant/{{.ProjectName}}:v{{ .Major }}
      - thomaspoignant/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}

brews:
  - # Github repository to push the tap to.
    tap:
      owner: thomaspoignant
      name: homebrew-tap

    caveats: "GO-feature-flag-relay-proxy is a proxy application to manage your feature flags."
    homepage: "https://github.com/thomaspoignant/go-feature-flag-relay-proxy"
    description: "GO-feature-flag-relay-proxy is a proxy application to manage your feature flags."
    skip_upload: auto

scoop:
  # Template for the url which is determined by the given Token (github or gitlab)
  url_template: "http://github.com/thomaspoignant/go-feature-flag-relay-proxy/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

  # Repository to push the app manifest to.
  bucket:
    owner: thomaspoignant
    name: scoop
  # The project name and current git tag are used in the format string.
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  # Your app's homepage.
  homepage: "https://github.com/thomaspoignant/go-feature-flag-relay-proxy"
  # Your app's description.
  description: "GO-feature-flag-relay-proxy is a proxy application to manage your feature flags."
  # Your app's license
  license: MIT

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^testdata:'
      - '^.github'
