repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.45.2
    hooks:
      - id: golangci-lint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
