name: Release
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.18.0'
      - run: go install github.com/goreleaser/goreleaser
      - run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
